/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampusRouteImport } from './routes/$campus'
import { Route as AzizNagarRouteImport } from './routes/aziz-nagar'
import { Route as CampusAboutRouteImport } from './routes/$campus.about'
import { Route as CampusActivitiesRouteImport } from './routes/$campus.activities'
import { Route as CampusAnnouncementsRouteImport } from './routes/$campus.announcements'
import { Route as CampusClubsRouteImport } from './routes/$campus.clubs'
import { Route as CampusEventsRouteImport } from './routes/$campus.events'
import { Route as CampusGalleryRouteImport } from './routes/$campus.gallery'
import { Route as CampusPrincipalRouteImport } from './routes/$campus.principal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/$campus',
  path: '/$campus',
  getParentRoute: () => rootRouteImport,
} as any)
const AzizNagarRoute = AzizNagarRouteImport.update({
  id: '/aziz-nagar',
  path: '/aziz-nagar',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusAboutRoute = CampusAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CampusRoute,
} as any)
const CampusActivitiesRoute = CampusActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => CampusRoute,
} as any)
const CampusAnnouncementsRoute = CampusAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => CampusRoute,
} as any)
const CampusClubsRoute = CampusClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => CampusRoute,
} as any)
const CampusEventsRoute = CampusEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CampusRoute,
} as any)
const CampusGalleryRoute = CampusGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => CampusRoute,
} as any)
const CampusPrincipalRoute = CampusPrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => CampusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$campus': typeof CampusRouteWithChildren
  '/aziz-nagar': typeof AzizNagarRoute
  '/$campus/about': typeof CampusAboutRoute
  '/$campus/activities': typeof CampusActivitiesRoute
  '/$campus/announcements': typeof CampusAnnouncementsRoute
  '/$campus/clubs': typeof CampusClubsRoute
  '/$campus/events': typeof CampusEventsRoute
  '/$campus/gallery': typeof CampusGalleryRoute
  '/$campus/principal': typeof CampusPrincipalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$campus': typeof CampusRouteWithChildren
  '/aziz-nagar': typeof AzizNagarRoute
  '/$campus/about': typeof CampusAboutRoute
  '/$campus/activities': typeof CampusActivitiesRoute
  '/$campus/announcements': typeof CampusAnnouncementsRoute
  '/$campus/clubs': typeof CampusClubsRoute
  '/$campus/events': typeof CampusEventsRoute
  '/$campus/gallery': typeof CampusGalleryRoute
  '/$campus/principal': typeof CampusPrincipalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$campus': typeof CampusRouteWithChildren
  '/aziz-nagar': typeof AzizNagarRoute
  '/$campus/about': typeof CampusAboutRoute
  '/$campus/activities': typeof CampusActivitiesRoute
  '/$campus/announcements': typeof CampusAnnouncementsRoute
  '/$campus/clubs': typeof CampusClubsRoute
  '/$campus/events': typeof CampusEventsRoute
  '/$campus/gallery': typeof CampusGalleryRoute
  '/$campus/principal': typeof CampusPrincipalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$campus'
    | '/aziz-nagar'
    | '/$campus/about'
    | '/$campus/activities'
    | '/$campus/announcements'
    | '/$campus/clubs'
    | '/$campus/events'
    | '/$campus/gallery'
    | '/$campus/principal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$campus'
    | '/aziz-nagar'
    | '/$campus/about'
    | '/$campus/activities'
    | '/$campus/announcements'
    | '/$campus/clubs'
    | '/$campus/events'
    | '/$campus/gallery'
    | '/$campus/principal'
  id:
    | '__root__'
    | '/'
    | '/$campus'
    | '/aziz-nagar'
    | '/$campus/about'
    | '/$campus/activities'
    | '/$campus/announcements'
    | '/$campus/clubs'
    | '/$campus/events'
    | '/$campus/gallery'
    | '/$campus/principal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampusRoute: typeof CampusRouteWithChildren
  AzizNagarRoute: typeof AzizNagarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$campus': {
      id: '/$campus'
      path: '/$campus'
      fullPath: '/$campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aziz-nagar': {
      id: '/aziz-nagar'
      path: '/aziz-nagar'
      fullPath: '/aziz-nagar'
      preLoaderRoute: typeof AzizNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$campus/about': {
      id: '/$campus/about'
      path: '/about'
      fullPath: '/$campus/about'
      preLoaderRoute: typeof CampusAboutRouteImport
      parentRoute: typeof CampusRoute
    }
    '/$campus/activities': {
      id: '/$campus/activities'
      path: '/activities'
      fullPath: '/$campus/activities'
      preLoaderRoute: typeof CampusActivitiesRouteImport
      parentRoute: typeof CampusRoute
    }
    '/$campus/announcements': {
      id: '/$campus/announcements'
      path: '/announcements'
      fullPath: '/$campus/announcements'
      preLoaderRoute: typeof CampusAnnouncementsRouteImport
      parentRoute: typeof CampusRoute
    }
    '/$campus/clubs': {
      id: '/$campus/clubs'
      path: '/clubs'
      fullPath: '/$campus/clubs'
      preLoaderRoute: typeof CampusClubsRouteImport
      parentRoute: typeof CampusRoute
    }
    '/$campus/events': {
      id: '/$campus/events'
      path: '/events'
      fullPath: '/$campus/events'
      preLoaderRoute: typeof CampusEventsRouteImport
      parentRoute: typeof CampusRoute
    }
    '/$campus/gallery': {
      id: '/$campus/gallery'
      path: '/gallery'
      fullPath: '/$campus/gallery'
      preLoaderRoute: typeof CampusGalleryRouteImport
      parentRoute: typeof CampusRoute
    }
    '/$campus/principal': {
      id: '/$campus/principal'
      path: '/principal'
      fullPath: '/$campus/principal'
      preLoaderRoute: typeof CampusPrincipalRouteImport
      parentRoute: typeof CampusRoute
    }
  }
}

interface CampusRouteChildren {
  CampusAboutRoute: typeof CampusAboutRoute
  CampusActivitiesRoute: typeof CampusActivitiesRoute
  CampusAnnouncementsRoute: typeof CampusAnnouncementsRoute
  CampusClubsRoute: typeof CampusClubsRoute
  CampusEventsRoute: typeof CampusEventsRoute
  CampusGalleryRoute: typeof CampusGalleryRoute
  CampusPrincipalRoute: typeof CampusPrincipalRoute
}

const CampusRouteChildren: CampusRouteChildren = {
  CampusAboutRoute: CampusAboutRoute,
  CampusActivitiesRoute: CampusActivitiesRoute,
  CampusAnnouncementsRoute: CampusAnnouncementsRoute,
  CampusClubsRoute: CampusClubsRoute,
  CampusEventsRoute: CampusEventsRoute,
  CampusGalleryRoute: CampusGalleryRoute,
  CampusPrincipalRoute: CampusPrincipalRoute,
}

const CampusRouteWithChildren =
  CampusRoute._addFileChildren(CampusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampusRoute: CampusRouteWithChildren,
  AzizNagarRoute: AzizNagarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
